# Nixpacks configuration for Railway deployment

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.start]
cmd = "./railway_start.sh"

[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"