# Railway Configuration for Shrimp Annotation Pipeline

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/app/railway_start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60