# Railway Configuration for Shrimp Annotation Pipeline

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "/app/railway_start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 120