#!/bin/bash

echo "🔐 GitHub Authentication Setup"
echo "=============================="
echo ""
echo "You need a Personal Access Token to push to GitHub."
echo ""
echo "Step 1: Create a Personal Access Token"
echo "1. Open this URL in your browser:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "2. Settings for the token:"
echo "   - Note: shrimp-annotation-pipeline"
echo "   - Expiration: 30 days (or your preference)"
echo "   - Scopes: Check ✅ 'repo' (all repo permissions)"
echo ""
echo "3. Click 'Generate token'"
echo "4. COPY THE TOKEN - you won't see it again!"
echo ""
echo "Step 2: Use the token to push"
echo "================================"
echo ""
echo "Run this command:"
echo "git push -u origin main"
echo ""
echo "When prompted:"
echo "Username: adelatif11-teramina"
echo "Password: [PASTE YOUR TOKEN HERE]"
echo ""
echo "Alternative: Set up token in git config (more permanent):"
echo "git config --global credential.helper store"
echo "Then push once with your token, and it will be saved."
echo ""
echo "Ready? Generate your token at:"
echo "https://github.com/settings/tokens/new"