"""Initial production schema

Revision ID: eb64a6ba0005
Revises: 
Create Date: 2025-10-02 19:00:40.192471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb64a6ba0005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_created', 'documents', ['created_at'], unique=False)
    op.create_index('idx_document_source_status', 'documents', ['source', 'status'], unique=False)
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active_role', 'users', ['is_active', 'role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.String(length=50), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sentence_doc_processed', 'sentences', ['document_id', 'processed'], unique=False)
    op.create_index('idx_sentence_doc_sent', 'sentences', ['document_id', 'sent_id'], unique=False)
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_processed'), 'sentences', ['processed'], unique=False)
    op.create_index(op.f('ix_sentences_sent_id'), 'sentences', ['sent_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('candidate_type', sa.String(length=20), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('model_info', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_confidence', 'candidates', ['confidence'], unique=False)
    op.create_index('idx_candidate_source_type', 'candidates', ['source', 'candidate_type'], unique=False)
    op.create_index('idx_candidate_status_priority', 'candidates', ['status', 'priority_score'], unique=False)
    op.create_index(op.f('ix_candidates_candidate_type'), 'candidates', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_candidates_confidence'), 'candidates', ['confidence'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_priority_score'), 'candidates', ['priority_score'], unique=False)
    op.create_index(op.f('ix_candidates_processed'), 'candidates', ['processed'], unique=False)
    op.create_index(op.f('ix_candidates_source'), 'candidates', ['source'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sa.String(length=20), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('time_spent', sa.Float(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annotation_doc_sent', 'annotations', ['document_id', 'sentence_id'], unique=False)
    op.create_index('idx_annotation_latest', 'annotations', ['is_latest', 'decision'], unique=False)
    op.create_index('idx_annotation_user_decision', 'annotations', ['user_id', 'decision'], unique=False)
    op.create_index(op.f('ix_annotations_annotation_type'), 'annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_decision'), 'annotations', ['decision'], unique=False)
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_index(op.f('ix_annotations_is_latest'), 'annotations', ['is_latest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_is_latest'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_decision'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_annotation_type'), table_name='annotations')
    op.drop_index('idx_annotation_user_decision', table_name='annotations')
    op.drop_index('idx_annotation_latest', table_name='annotations')
    op.drop_index('idx_annotation_doc_sent', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_source'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_processed'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_priority_score'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_confidence'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_type'), table_name='candidates')
    op.drop_index('idx_candidate_status_priority', table_name='candidates')
    op.drop_index('idx_candidate_source_type', table_name='candidates')
    op.drop_index('idx_candidate_confidence', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_sentences_sent_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_processed'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_index('idx_sentence_doc_sent', table_name='sentences')
    op.drop_index('idx_sentence_doc_processed', table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_active_role', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_index('idx_document_source_status', table_name='documents')
    op.drop_index('idx_document_created', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
